version: '2'
services:
  intensecoin:
    image: jc21/intensecoind:beta
    ports:
      - ${p2p_bind_port}:${p2p_bind_port}
      - ${rpc_bind_port}:${rpc_bind_port}
    environment:
      - P2P_BIND_PORT=${p2p_bind_port}
      - RPC_BIND_PORT=${rpc_bind_port}
      - RPC_BIND_IP=0.0.0.0
      - DAEMON_EXTRA_ARGS=--confirm-external-bind ${daemon_extra_args}
    volumes:
      - /root/.intensecoin
    labels:
      io.rancher.container.hostname_override: container_name
